### ISSUE TITLE
Not working with Kakoune v2018.09.04

### ISSUE THREAD

**Issue by andreyorst** [Delapouite/kakoune-text-objects#1]
Seems like this plugin isn't working with current release version of Kakoune v2018.09.04.

Pressing <kbd>alt</kbd>+<kbd>i</kbd> <kbd>)</kbd> results in the following error:
```kak
Error: 1:1: 'text-object-block' no such command: 'try %| exec <a-i> '(' | catch %| exec / \Q '(' \E <ret> ; exec <a-i> '(' |'
```

**Comment by Delapouite** [comment]
Thanks. It should be addressed in https://github.com/Delapouite/kakoune-text-objects/commit/8f7e2c759381d8c50e0714b157246b976e0941d2
